### ISSUE TITLE
Conditional confirmation of correct functioning

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-core#2]
Assuming that the behavior shown below is the expected one, I can confirm that the "linkage" between the app and KendoUI plugin functions correctly. This is especially true for the autocomplete control :-)

![image](https://cloud.githubusercontent.com/assets/2712405/11453206/af859304-95cf-11e5-8959-81c27093fc43.png)

(While I would likely add a new page for showing Aurelia-KendoUI plugin artifacts, this approach saved some time without compromising its purpose)

**Comment by JeroenVinke** [comment]
It is indeed the expected behaviour :+1:

**Comment by adriatic** [comment]
... meaning that we have the first winner of the day :-)

**Comment by JeroenVinke** [comment]
To be honest, this is the easy one :)

**Comment by adriatic** [comment]
Nevertheless - I like when things work as expected across more than one computer :-)
